services:
- name: iris_7
  envVars:
    - key: FLASK_APP
      value: "app.py"
    - key: FLASK_RUN_HOST
      value: "0.0.0.0"
    - key: FLASK_RUN_PORT
      value: "8080"  
  healthCheckPath: /  
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -b 0.0.0.0:8080 -w 4 app:app
  useDocker: true