name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Build and Push Docker Image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app

      - name: Deploy on Render
        run: |
          curl -X POST "https://api.render.com/v1/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"name": "my-flask-app", "githubRepo": "randomMeow7/ML_Project", "branch": "main", "buildCommand": "docker pull ${{ secrets.DOCKER_USERNAME }}/my-flask-app"}'